[build]
  command = "gatsby build"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "ALLOW-FROM taxfoundation.org"
    Content-Security-Policy = "frame-ancestors 'self' https://*.taxfoundation.org"